name: example-environment
dependencies:
  - numpy
  - cdsapi
  - pandas
  - netCDF4
  - dask
  - xarray
  - matplotlib
  - cartopy
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - leafmap
  - importlib-metadata
  - cartopy