name: ccdown
channels:
  - conda-forge
dependencies:
  - python=3.7
  - ipython
  - numpy
  - cdsapi
  - pandas
  - netCDF4
  - dask-core
  - xarray
  - matplotlib
  - cartopy
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - leafmap
  - importlib-metadata
  - cartopy
  - pip
  - pip:
    - https://github.com/joshloyal/sliced/archive/243bde2.zip
    - cdsapi
    - -e .  