name: ccdown
channels:
  - conda-forge
dependencies:
  - numpy
  - cdsapi
  - pandas
  - netCDF4
  - dask
  - xarray
  - matplotlib
  - cartopy
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - leafmap
  - importlib-metadata
  - cartopy
  - pip
  - pip:
    - https://github.com/joshloyal/sliced/archive/243bde2.zip
    - cdsapi
    - -e .  